import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      disallow: [
        "/top/",
        "/*đánh lô đề*",
        "/*daftar slot*",
        "/*game+đổi+thưởng*",
        "/*airdrop*",
        "/*SOSO+CASINO*",
        "/*binance*",
        "/*WeChat*",
        "/*telegram*",
        "/*Telegram*",
        "/*bleesvanos*",
        "/*wibu69*",
        "/*javhd*",
        "/*@cryptoenthus2*",
        "/*3dbet slot*",
        "/*c65694*",
        "/*d43369*",
        "/*ElSX*",
        "/*f56669*",
        "/*f66584*",
        "/*h12831*",
        "/*h89796*",
        "/*i12449*",
        "/*j26592*",
        "/*j38891*",
        "/*j93673*",
        "/*k62342*",
        "/*king88bet*",
        "/*kingbet88*",
        "/*l93972*",
        "/*liga365*",
        "/*m25186*",
        "/*m77385*",
        "/*mbak4d*",
        "/*murah4d*",
        "/*n74642*",
        "/*n88 slot*",
        "/*o81648*",
        "/*o84175*",
        "/*OGDx*",
        "/*petir138*",
        "/*qqwin88*",
        "/*r18979*",
        "/*r53518*",
        "/*s18428*",
        "/*s88828*",
        "/*u12745*",
        "/*v86538*",
        "/*v96366*",
        "/*vipbet88 slot*",
        "/*w46334*",
        "/*we88*",
        "/*win77 slot*",
        "/*win777 slot*",
        "/*x54585*",
        "/*YrKR*",
        "/*z21496*",
        "/*SOSO20CASINO*",
        "/*casino*",
        "/*188bet*",
        "/*s26bet*",
        "/*S26Bet*",
        "/*S26bet*",
        "/*S26BET*",
        "/*ivf###*",
        "/*ibb###*",
        "/*229 8881*",
        "/*AppStore*",
        "/*1-305-590-1878*",
        "/*Sex*",
        "/*xxxx*",
        "/*Sodo6*",
        "/*[*",
        "/*《*",
        "/*』*",
        "/*】*",
        "/*【*",
        "/*sudo6*",
        "/*B6H3319*",
        "/*में*",
        "/*PDF9*",
        "/*〖*",
        "/*lienge89867*",
        "/*Web:*",
        "/*☞*",
        "/*E2%98%9E*",
        "/*url:*",
        "/*gboplay*",
        "/*bets899*",
        "/*btr788*",
        "/*indoplay88*",
        "/*mq168*",
        "/*eggcsite*",
        // Blocks win77, win777, etc.
        "/*win77*",
        // Blocks anything ending in .live
        "/*.live*",
        "/*⭕*",
        "/*⭐*",
        "/danh-muc/tim-kiem?name=*.com",
        "/danh-muc/tim-kiem?name=*.cc",
        "/danh-muc/tim-kiem?name=*.vip",
        "/danh-muc/tim-kiem?name=*.net",
        "/danh-muc/tim-kiem?name=*.CC",
        "/danh-muc/tim-kiem?name=*.wink",
        "/danh-muc/tim-kiem?name=*.live",
        "/danh-muc/tim-kiem?name=*.LIVE",
        "/nguoi-dung/thong-tin-ca-nhan",
        "/nguoi-dung/lich-su-don-hang",
        "/nguoi-dung/so-dia-chi",
        "/gio-hang",
      ],
    },
  };
}
